"""Public schema contract for the JudgeFlow demo."""

from .schemas import (
    AppealDecision,
    ArtifactEnvelope,
    AttributionReport,
    CounterArgument,
    DecisionRecord,
    EvidenceBundle,
    EvidenceRef,
    FactRecord,
    HumanApproval,
    InferenceRecord,
    Policy,
    PolicyCondition,
    PolicyProposal,
    PolicySnapshot,
    ReplayReport,
    RiskArgument,
    ToolFailure,
    WorkOrder,
)
from .database import (
    Appeal,
    AppealStatus,
    Artifact,
    Base,
    Case,
    CaseStatus,
    DomainEvent,
    EvolutionStatus,
    PolicyEvolution,
    PolicyRow,
    ReplayRun,
    WorkOrderRow,
    WorkOrderStatus,
)

TOP_LEVEL_SCHEMAS = (
    WorkOrder,
    ArtifactEnvelope,
    EvidenceRef,
    FactRecord,
    InferenceRecord,
    ToolFailure,
    EvidenceBundle,
    RiskArgument,
    CounterArgument,
    DecisionRecord,
    AppealDecision,
    AttributionReport,
    PolicyProposal,
    ReplayReport,
    HumanApproval,
    Policy,
    PolicyCondition,
    PolicySnapshot,
)

__all__ = [model.__name__ for model in TOP_LEVEL_SCHEMAS] + [
    "TOP_LEVEL_SCHEMAS",
    "Appeal",
    "AppealStatus",
    "Artifact",
    "Base",
    "Case",
    "CaseStatus",
    "DomainEvent",
    "EvolutionStatus",
    "PolicyEvolution",
    "PolicyRow",
    "ReplayRun",
    "WorkOrderRow",
    "WorkOrderStatus",
]
